// SPDX-License-Identifier: MIT
pragma solidity >0.4.21;

// FlashSyn harness skeleton. Pairs with manifest.toml in this directory.
// This is the ONLY code you hand-write. Everything below the preamble (the data
// collectors) is generated by the engine from the manifest's actions.
//
// This file is a copy-me skeleton with placeholder addresses — it is NOT meant to
// compile as-is. Replace the interfaces, addresses, funding, and profitSummary with
// your protocol's, keeping the token variable names in sync with manifest tokenInfo.

import {DSTest} from "ds-test/test.sol";
import {Vm} from "forge-std/Vm.sol";
import {stdCheats} from "forge-std/stdlib.sol";
import {Strings} from "mylib/StringCon.sol";


// TODO 1. Declare an interface per contract your actions call. Only the functions
// you use. USDT-style tokens whose approve/transfer return nothing need their own
// interface (no `returns (bool)`).
interface IToken {
    function approve(address spender, uint256 value) external returns (bool);
    function balanceOf(address account) external view returns (uint256);
    function transfer(address to, uint256 value) external returns (bool);
}

interface IPool {
    function exchange(int128 i, int128 j, uint256 dx, uint256 min_dy) external;
}

interface IVault {
    function deposit(uint256 amount) external;
    function withdraw(uint256 shares) external;
    function balanceOf(address account) external view returns (uint256);
}

interface IRouter {
    function swapExactTokensForTokens(uint256 amountIn, uint256 amountOutMin,
        address[] calldata path, address to, uint256 deadline) external;
}

contract Template is DSTest, stdCheats {
    Vm internal constant vm = Vm(HEVM_ADDRESS);
    address payable constant attacker = payable(address(uint160(uint256(keccak256(abi.encodePacked("attacker"))))));

    // TODO 2. State vars for every contract your actions reference. The token variable
    // names here MUST match manifest [token_info] (TOKENA, TOKENB, VAULT). Use real
    // mainnet addresses at the fork block.
    IToken  internal constant TOKENA = IToken(address(0x0000000000000000000000000000000000000001));
    IToken  internal constant TOKENB = IToken(address(0x0000000000000000000000000000000000000002));
    IVault  internal constant VAULT  = IVault(address(0x0000000000000000000000000000000000000003));
    IPool   internal constant POOL   = IPool(address(0x0000000000000000000000000000000000000004));
    IRouter internal constant ROUTER = IRouter(address(0x0000000000000000000000000000000000000005));

    // Any extra vars a multi-call action references also live here (e.g. a swap path,
    // temp structs, a second attacker account for liquidations).
    address[] path;

    // TODO 3. setUp() runs before every test. Fork happens via the CLI flags. Here you:
    //   (a) fund the attacker with the manifest's initial_balances, and
    //   (b) grant approvals.  Leave vm.startPrank(attacker) open at the end.
    function setUp() public {
        vm.label(attacker, "Attacker");

        // --- (a) Funding. Pick whichever works for each token: ---
        // Mintable token via a privileged minter (see examples/harvest_usdt):
        //     vm.startPrank(TOKEN.someMinter()); TOKEN.mint(attacker, 50000000e6); vm.stopPrank();
        // Any ERC20 via a direct balance-slot write (find the mapping slot; USDT=2, USDC=9):
        //     vm.store(address(TOKENA), keccak256(abi.encode(attacker, uint256(SLOT))), bytes32(uint256(50000000e6)));
        // Always assert it took, so a wrong slot fails loud instead of funding 0:
        //     require(TOKENA.balanceOf(attacker) == 50000000e6, "TOKENA funding failed");

        // --- (b) Approvals for every spender your actions use ---
        vm.startPrank(attacker);
        // TOKENA.approve(address(POOL), type(uint256).max);
        // TOKENA.approve(address(VAULT), type(uint256).max);
        // TOKENB.approve(address(ROUTER), type(uint256).max);
    }

    // TODO 4. Print the profit tokens, in the SAME ORDER as manifest profit_tokens.
    // The string must contain "FlashSyn"; the integers after it are parsed as balances.
    function profitSummary() public view returns (string memory) {
        return Strings.append(
            "FlashSyn: ",
            Strings.appendWithSpace(TOKENA.balanceOf(address(attacker)) / 1e6,
                                    TOKENB.balanceOf(address(attacker)) / 1e6)
        );
    }

    // ---- Everything above is the "preamble" the engine reads. Everything below is
    // ---- only for `flashsyn.py compile` (sanity) and `deps` (dependency graph); the
    // ---- collectors used by collect/synthesize are generated from the manifest.

    // TODO 5. (Optional) one testExample per action: run just that action between the
    // separators, prefixed by anything it depends on. End with revert(""). You can omit
    // these — synthesis doesn't need them — but they let `compile`/`deps` validate.
    function testExample0() public {
        emit log("=================== Separator ==================");
        // POOL.exchange(0, 1, 1000000 * 1e6, 0);
        emit log("=================== Separator ==================");
        revert("");
    }
}
